name: Source Coverage
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - development

jobs:
  coverage:
    name: test
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: llvm-tools-preview
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          RUSTFLAGS: "-C instrument-coverage"
          RUSTDOCFLAGS: "-C instrument-coverage"
          LLVM_PROFILE_FILE: "coverage_data-%p-%m.profraw"
      - id: coverage
        name: Prepare coverage data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cargo install grcov
          grcov . -s . --binary-path ./target/debug -t coveralls --branch --ignore-not-existing -o ./target/coveralls_coverage.json --token "${GITHUB_TOKEN}" --vcs-branch $GITHUB_REF_NAME
      - id: archive-coverage
        name: archive-coverage
        uses: actions/upload-artifact@v3
        with:
          path: target/coveralls.json
          name: coveralls-coverage
      - name: Coveralls upload
        uses: toshke/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./target/coveralls_coverage.json
          file-format: coveralls